keycloak:
  serverUrl: ${KEYCLOAK_SERVER_URL}
  master:
    realm: ${KEYCLOAK_MASTER_REALM}
    clientId: ${KEYCLOAK_MASTER_CLIENTID}
    clientSecret: ${KEYCLOAK_MASTER_CLIENT_SECRET}
    username: ${KEYCLOAK_MASTER_USERNAME}
    password: ${KEYCLOAK_MASTER_PASSWORD}
  
logging:
  level:
    com:
      skcc:
        cloudz:
          zcp: DEBUG
    io:
      kubernetes:
        client: DEBUG
    org:
      hibernate: DEBUG
      keycloak: DEBUG
      springframework:
        security: DEBUG
        web: DEBUG
        
kube:
  client:
    api:
      output:
        pretty: true
  server:
    apiserver:
      endpoint: ${KUBE_APISERVER_URL}
    
server:
  port: 8181
zcp:
  keycloak:
    realm: zcp
  kube:
    namespace: zcp-system

jenkins:
  url: https://jenkins.cloudzcp.io
  token: username:api-token
  template: 
    folder: classpath:jenkins/folder.xml

role:
  cluster:
    cluster-admin:
    - cluster-admin
    member:
  namespace:
    admin:
    - log-manager
    - catalog-manager
    - ${namespace}-admin
    deploy-manager:
    - log-manager
    - ${namespace}-deploy-manager
    developer:
    - ${namespace}-developer
  jenkins:
    admin: ${namespace}-admin
    deploy-manager: ${namespace}-deploy-manager
    developer: ${namespace}-developer