keycloak:
  serverUrl: http://keycloak.cberry.xyz/auth
  master:
    realm: zcp
    clientId: account
    clientSecret: 611c87d9-37f3-4078-b500-542cf419b113
    password: admin1234
    username: 1800275@partner.skcc.com

logging:
  level:
    com:
      skcc:
        cloudz:
          zcp: DEBUG
    org:
      hibernate: DEBUG
      springframework:
        security: DEBUG
        web: DEBUG

kube:
  client:
    api:
      output:
        pretty: true
  server:
    apiserver:
      endpoint: https://169.56.69.242:23078
    
server:
  port: 8282
zcp:
  keycloak:
    realm: zcp
  kube:
    namespace: zcp-system

role:
  cluster:
    cluster-admin:
    - cluster-admin
    member:
  namespace:
    admin:
    - log-manager
    - catalog-manager
    - ${namespace}-admin
    deploy-manager:
    - log-manager
    - ${namespace}-deploy-manager
    developer:
    - ${namespace}-developer
