apiVersion: v1
kind: Pod
metadata:
  name: web-ssh-${name.suffix}
  namespace: ${namespace}
spec:
  #serviceAccountName: zcp-system-sa-cloudzcp-admin
  #securityContext:
  #  runAsUser: 1000
  containers:
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh"]
    args:
    - "-c"
    - |
        echo 'OK' > status;
        cmd='cat status';

        while true; do

        res=$(eval $cmd);
        if [ "$res" != 'OK' ]; then;
        echo "Terminate process (status: $res).";
        exit;
        fi;

        echo hello;
        sleep 10;
        done
    securityContext:
      #runAsUser: 0  #root
      allowPrivilegeEscalation: false